;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        org-delete-char
        org-end-of-line
        org-self-insert-command
        paredit-forward-delete
        ))

(setq mc/cmds-to-run-once
      '(
        ))
